version: '3.8'

services:

  web:
    build: .
    command: poetry run uvicorn drunkMate.api.__init__:create_app --factory --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/drunkMate
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION_STRING=mongodb://admin:password@mongo:27017/
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
